"""renaming again

Revision ID: 319ee51c0f2e
Revises: 962346070ea3
Create Date: 2025-11-23 23:29:23.981424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '319ee51c0f2e'
down_revision = '962346070ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
