"""removing link table

Revision ID: 738ba0c45e4f
Revises: f61a5961290d
Create Date: 2025-11-23 23:27:23.795937

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '738ba0c45e4f'
down_revision = 'f61a5961290d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exerciseworkoutlink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exerciseworkoutlink',
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('exerciseworkoutlink_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('exerciseworkoutlink_workout_id_fkey')),
    sa.PrimaryKeyConstraint('exercise_id', 'workout_id', name=op.f('exerciseworkoutlink_pkey'))
    )
    # ### end Alembic commands ###
