"""link table

Revision ID: 7dca4e2d2c19
Revises: c254cfd8b25c
Create Date: 2025-11-23 21:59:47.796699

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7dca4e2d2c19'
down_revision = 'c254cfd8b25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exerciseworkoutlink',
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('workout_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'workout_id')
    )
    op.drop_constraint(op.f('exercise_workout_id_fkey'), 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'workout_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('exercise_workout_id_fkey'), 'exercise', 'workout', ['workout_id'], ['id'])
    op.drop_table('exerciseworkoutlink')
    # ### end Alembic commands ###
