"""add exercise and workout back in

Revision ID: 8e5b871edee7
Revises: c2900a9a6cc6
Create Date: 2025-11-23 21:18:26.127261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8e5b871edee7'
down_revision = 'c2900a9a6cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
