"""renaming testing column in workouts

Revision ID: 962346070ea3
Revises: 738ba0c45e4f
Create Date: 2025-11-23 23:28:40.163983

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '962346070ea3'
down_revision = '738ba0c45e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
