"""one last rename

Revision ID: bb7018702516
Revises: bdbad2d6882f
Create Date: 2025-11-23 23:31:00.744429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb7018702516'
down_revision = 'bdbad2d6882f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('workout', 'workouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workouts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('workout', 'exercises')
    # ### end Alembic commands ###
