"""renaming for real this time

Revision ID: bdbad2d6882f
Revises: 319ee51c0f2e
Create Date: 2025-11-23 23:30:32.747493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdbad2d6882f'
down_revision = '319ee51c0f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workouts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('workout', 'testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('testing', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('workout', 'workouts')
    # ### end Alembic commands ###
