"""testing exercise

Revision ID: c254cfd8b25c
Revises: 8e5b871edee7
Create Date: 2025-11-23 21:50:50.009603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c254cfd8b25c'
down_revision = '8e5b871edee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
