"""fix exercise table

Revision ID: c2900a9a6cc6
Revises: 549eed53fbce
Create Date: 2025-11-23 21:00:18.441568

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c2900a9a6cc6'
down_revision = '549eed53fbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('workout_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'exercise', 'workout', ['workout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'workout_id')
    # ### end Alembic commands ###
