"""testing json column in exercises

Revision ID: f61a5961290d
Revises: 7dca4e2d2c19
Create Date: 2025-11-23 23:02:34.782969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f61a5961290d'
down_revision = '7dca4e2d2c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('testing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'testing')
    # ### end Alembic commands ###
